### ISSUE TITLE
[Peer Review] Code review for "Analysis of readability and structural accuracy of the OBO Foundry ontologies"

### ISSUE THREAD

**Issue by cthoyt** [fanavarro/lexical-analysis-obo-foundry#4]
Dear @fanavarro,

I have been invited to review your article "Analysis of readability and structural accuracy of the OBO Foundry ontologies" for the Journal of Biomedical Semantics.

You'll also see I've left quite a few issues on this repository ranging from specific code suggestions to more philosophical discussions. I've meant all in good faith - have like the concept of your paper and with some additional effort I think it will be publishable. However, I'm likely one of the pickiest code reviewers in the entire bioinformatics community, so we're going to make your repository the best it can possibly be before the review is done. The remainder of my review of the manuscript itself will be delivered through the manuscript management system provided by the journal.

Greetings from Bonn, Germany. Have a nice day.

-Charlie Hoyt

Related issues:

- [x] #1 Add tutorial on how to reproduce results
- [ ] #2 Make zenodo archive of code and data
- [ ] #3 Make sure scripts can be run
- [x] #5
- [x] #6 
- [x] #7

Unfortunately, some of the typical things I review aren't possible yet because of the lack of documentation, so I will add to this list after they become available.

**Comment by fanavarro** [comment]
Dear @cthoyt,

Thanks so much for your effort in this valuable revision. I appreciate your work doing this and I agree with the points you have highlighted; therefore I will be working on this during the next days in order to address your comments.

Greetings and thanks again,
Francisco Abad.

**Comment by fanavarro** [comment]
I've addressed most of the issues you created. I'm closing what I've done with an explanatory comment. Nonetheless, feel free to reopen any issue if you think it is not completely achieved.

Regards,
Francisco Abad
